name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Needed to push to GHCR
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # ghcr.io/<owner>/<repo>

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (module Accumulator)
        run: mvn -B -DskipTests package --file Accumulator/pom.xml

      - name: Prepare app.jar for Docker build
        run: |
          JAR_PATH=$(ls Accumulator/target/*.jar | head -n 1)
          cp "$JAR_PATH" app.jar
          ls -l app.jar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-artifact
          path: Accumulator/target/*.jar

      - name: Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            # enable semver tags on releases if you create git tags like v1.2.3
            type=semver,pattern={{version}}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Accumulator/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}   # push only on main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
